In [163]:
import bs4 as bs
import datetime as dt
import os
import pickle
import requests
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import lxml
import numpy.random as rn

In [165]:
russell = pd.read_csv("IWV_holdings.csv")[:-100]

In [166]:
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
response = requests.get(url)
soup = bs.BeautifulSoup(response.text, 'html.parser')
table = soup.find('table', {'id': 'constituents'})
df = pd.read_html(str(table))[0]
sp500tickers = df['Symbol'].tolist()

C:\Users\guibi\AppData\Local\Temp\ipykernel_11076\1842220428.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]


In [168]:
data = yf.download(list(russell['Ticker']), start='2010-01-01', end='2024-09-01')
data = data['Adj Close']

[*********************100%***********************]  2579 of 2579 completed

14 Failed downloads:
['LENB', 'BRKB', 'UHALB', 'METCV', 'BFB', 'GEFB', 'MOGA', 'XTSLA', 'BFA', 'CWENA', 'HEIA', 'LGFA', 'LGFB', 'MSFUT']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')


In [169]:
data_filtered = data[-1250:].dropna(axis = 1)

In [170]:
rn.seed(123)
data_small = data_filtered.iloc[:,rn.choice(1250, 100, replace = False)]

log_returns_data = np.log(data_small).diff()
log_returns_data.to_csv("returns_data100.csv")

In [171]:
rn.seed(123)
data_small = data_filtered.iloc[:,rn.choice(1250, 500, replace = False)]

log_returns_data = np.log(data_small).diff()
log_returns_data.to_csv("returns_data500.csv")

In [173]:
rn.seed(123)
data_small = data_filtered.iloc[:,rn.choice(1250, 1000, replace = False)]

log_returns_data = np.log(data_small).diff()
log_returns_data.to_csv("returns_data1000.csv")

In [182]:
print(np.where(log_returns_data.columns == 'AAPL'))
print(np.where(log_returns_data.columns == 'GOOG'))
print(np.where(log_returns_data.columns == 'BAC'))
print(np.where(log_returns_data.columns == 'GS'))

(array([118], dtype=int64),)
(array([797], dtype=int64),)
(array([55], dtype=int64),)
(array([960], dtype=int64),)


# Long History

In [40]:
data = yf.download(list(russell['Ticker']), start='2005-01-01', end='2024-09-01')
data = data['Adj Close']

[*********************100%***********************]  2579 of 2579 completed

17 Failed downloads:
['BRKB', 'UHALB', 'METCV', 'BFB', 'GEFB', 'MOGA', 'XTSLA', 'BFA', 'CWENA', 'LENB', 'HEIA', 'LGFA', 'LGFB', 'MSFUT']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['KMI']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2005-01-01 -> 2024-09-01)')
['PARAA']: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Read timed out. (read timeout=10)"))
['WEN']: ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Read timed out."))


In [42]:
data_filtered = data.dropna(axis = 1)

In [116]:
rn.seed(105)
data_history = data_filtered.iloc[:,rn.choice(1290, 750, replace = False)]

log_returns_data = np.log(data_history).diff()
log_returns_data.to_csv("returns_data_long_750.csv")
data_history.to_csv("levels_data_long_750.csv")

In [126]:
np.where(data_history.columns == 'JPM')

(array([217], dtype=int64),)

In [193]:
data = yf.download((sp500tickers), start='2015-01-01', end='2024-09-01')
data = data['Adj Close']
data_filtered = data.dropna(axis = 1)

rn.seed(201)
data_history = data_filtered.iloc[:,rn.choice(471 , 100, replace = False)]

log_returns_data = np.log(data_history).diff()[1:]
log_returns_data.to_csv("returns_data_long_100.csv")
data_history.to_csv("levels_data_long_100.csv")

[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2015-01-01 -> 2024-09-01)')
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
